# Generated by Django 6.0.7 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('paused', 'Paused'), ('sold', 'Sold')],
                default='active',
                max_length=20,
            ),
        ),
    ]
