# Generated by Django 5.2.4 on 2025-08-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailverification_code_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
