# Generated by Django 5.2.4 on 2025-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_verification_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='passphrase',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
