# Generated by Django 5.2.4 on 2025-10-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_verification_passphrase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
