# Generated by Django 5.2.4 on 2025-11-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification_token',
            old_name='user_id',
            new_name='user',
        ),
    ]
